# Dockerfile.server
FROM python:3.12-slim

WORKDIR /legendary-goggles
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the dataset and server code
COPY . .

CMD ["python3", "-m", "src.api.rpc_server"]